language: objective-c
osx_image: xcode7.2
before_install:
    - gem install slather --no-rdoc --no-ri --no-document --quiet
script:
  - xctool test -workspace Example/HexKit.xcworkspace -scheme HexKit-Example -sdk iphonesimulator -destination 'name=iPhone 6' ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
  - pod lib lint
after_success:
  - cd $TRAVIS_BUILD_DIR && slather
